version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=talebound
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d talebound -U root" ]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgres://root:secret@postgres:5432/talebound?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

